### ISSUE TITLE
Unable to change web language.

### ISSUE THREAD

**Issue by DalenVigil** [guanicoe/ESPBug_PIO#3]
Follow the tutorial and the video. captive.html shows the correct file. When trying to run the python script in Terminal I get:

> Traceback (most recent call last):
  File "/Users/REDACTED/Desktop/ESPBug/web_converter/webConverter.py", line 8, in <module>
    from css_html_js_minify.minify import process_single_html_file, process_single_js_file, process_single_css_file
  File "/Users/REDACTED/Desktop/ESPBug/web_converter/css_html_js_minify/__init__.py", line 13, in <module>
    from .minify import (process_single_html_file, process_single_js_file,
  File "/Users/REDACTED/Desktop/ESPBug/web_converter/css_html_js_minify/minify.py", line 30, in <module>
    from anglerfish import (check_encoding, check_folder, make_logger,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/anglerfish/__init__.py", line 32, in <module>
    from anglerfish.get_clipboard import get_clipboard  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/anglerfish/get_clipboard.py", line 18, in <module>
    Clipboard = NamedTuple("Clipboard", fields=(("copy", callable),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1875, in NamedTuple
    return _make_nmtuple(typename, fields, module=module)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1800, in _make_nmtuple
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1800, in <dictcomp>
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 157, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: field fields annotation must be a type Got (('copy', <built-in function callable>), ('paste', <built-in function callable>)).
>

Anglerfish installed correctly, but I'm new, this is my first project, so I'm not sure what's screwy or how to fix it. My output looks nothing like what's shown in the video.

**Comment by Prompt-Injection** [comment]
Same Problem here. Please help.
